### ISSUE TITLE
Log4net 2.0.5 compatible version?

### ISSUE THREAD

**Issue by freeranger** [mperdeck/jsnlog.configurations#1]
Hi,

Is it possible to get a version of JSNLog.Log4Net which is dependent on/compatible with log4net 2.0.5?

This is the version of Common.Logging for Log4Net that you would need to reference: 
https://www.nuget.org/packages/Common.Logging.Log4Net1215

thanks

**Comment by mperdeck** [comment]
Just released a new version that depends on Common.Logging.Log4Net1215:
https://www.nuget.org/packages/JSNLog.Log4Net/

**Comment by freeranger** [comment]
Great, thanks
